spring:
  datasource:
    url: jdbc:mysql://localhost:6666/ProgramCenter?useUnicode=true&characterEncoding=utf-8
    username: ProgramCenter
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    ehcache:
      config: ehcache.xml
server:
  port: 8090
paperCenter-paper-api: http://ec2-54-222-191-27.cn-north-1.compute.amazonaws.com.cn:8080
paperCenter-web-api: http://ec2-54-222-191-27.cn-north-1.compute.amazonaws.com.cn:3000
userCenter: http://ec2-54-223-76-0.cn-north-1.compute.amazonaws.com.cn:8081
practiseDiary: http://ec2-54-223-215-20.cn-north-1.compute.amazonaws.com.cn:8080

programId: 5

#quizCenter: http://localhost:8087
quizCenter: http://ec2-54-223-35-144.cn-north-1.compute.amazonaws.com.cn:8080
