spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ProgramCenterTest?useUnicode=true&characterEncoding=utf-8
    username: ProgramCenterTest
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8090

paperCenter-paper-api: http://ec2-54-222-191-27.cn-north-1.compute.amazonaws.com.cn:8080
paperCenter-web-api: http://ec2-54-222-191-27.cn-north-1.compute.amazonaws.com.cn:3000

userCenter: http://localhost:10001
#userCenter: http://ec2-54-223-76-0.cn-north-1.compute.amazonaws.com.cn:8081
#practiseDiary: http://ec2-54-223-215-20.cn-north-1.compute.amazonaws.com.cn:8080
practiseDiary: http://localhost:10002
quizCenter: http://localhost:10003
programId: 5

flyway:
  locations: classpath:/db.migration
  url: jdbc:mysql://mysql:3307/ProgramCenterTest?useUnicode=yes&characterEncoding=UTF-8
  user: ProgramCenterTest
  password: 12345678